Revert accidental change while fixing clippy warnings
Chia-Network/chia_rs pull request #706
Opened 2024-09-09 15:44 UTC by AmineKhaldi

This is part of PR #703 that got conflicted by PR #705.

2024-09-09 16:45 UTC, altendky requested changes

2024-09-09 16:45 UTC, altendky commented on crates/chia-consensus/src/spendbundle_conditions.rs
> +    const QUOTE_BYTE_COST: u64 = 2 * TEST_CONSTANTS.cost_per_byte;
May  as well use the constant?

```suggestion
    const QUOTE_BYTE_COST: u64 = QUOTE_BYTES * TEST_CONSTANTS.cost_per_byte;
```

2024-09-09 20:49 UTC, Rigidity approved these changes

2024-09-11 15:20 UTC, arvidn approved these changes

2024-09-13 10:48 UTC, merged