add uncurry() function to clvm-utils
Chia-Network/chia_rs pull request #81
Opened 2022-11-12 10:01 UTC by arvidn

This adds an `uncurry()` function to `clvm-utils`. It's implemented to not allocate a new list for the arguments with the clvm allocator. This enables using it on a potential future read-only allocator.

2022-11-12 11:20 UTC, arvidn commented
the fuzzer isn't great right now, as the `make_tree()` utility function is recursive and so might blow out the stack. Making it iterative is on the list of future improvements.

2022-11-22 01:16 UTC, richardkiss commented on clvm-utils/src/uncurry.rs
> +fn unwrap3<'a>(node: Node<'a>) -> Result<(Node<'a>, Node<'a>, Node<'a>), ()> {
I think what you want here is `Option`, not `Result`.

2022-11-22 02:36 UTC, richardkiss requested changes
I'd say use `Option` rather than `Result` in many places here.

2022-11-22 13:06 UTC, arvidn commented on clvm-utils/src/uncurry.rs
> +pub fn uncurry(a: &Allocator, node: NodePtr) -> Result<(NodePtr, Vec<NodePtr>), ()> {
my understanding is that `Option` does not support the `?` operator, which is the whole point of returning it here. To be able to write succinct call sites

2022-11-22 18:55 UTC, richardkiss approved these changes
Lookin' good.

2022-11-22 19:34 UTC, merged